###
# Create a user (Sign Up)
POST http://127.0.0.1:8000/signup/
Content-Type: application/json

{
    "email": "kit@test.com",
    "password": "testpass123",
    "firstname": "Keith",
    "middlename": "C",
    "lastname": "Tapongot",
    "campus": "USTP-CDO",
    "college": "College of Information Technology",
    "department": "Department of TCM",
    "contactNumber": "09123456789",
    "role": [1]
}

###

# Log in to get token
POST http://127.0.0.1:8000/auth/token/login/
Content-Type: application/json

{
    "email": "wyn@test.com",
    "password": "testpass"
}

# Example token: de95d63d55190f47cf0ae40ea1c805752686f6a7

###

# Log out using token
POST http://127.0.0.1:8000/auth/token/logout/
Content-Type: application/json
Authorization: Token de95d63d55190f47cf0ae40ea1c805752686f6a7

{}

###

# Get authenticated user details
GET http://127.0.0.1:8000/auth/users/me/
Content-Type: application/json
Authorization: Token de95d63d55190f47cf0ae40ea1c805752686f6a7

{}

###

# Get a specific project
GET http://127.0.0.1:8000/get_project/1/
Content-Type: application/json
Authorization: Token de95d63d55190f47cf0ae40ea1c805752686f6a7

###

# Update a project
PUT http://127.0.0.1:8000/edit_project/3/
Content-Type: application/json
Authorization: Token de95d63d55190f47cf0ae40ea1c805752686f6a7

{
    "userID": 4
}

###

# Get accomplishment reports
GET http://127.0.0.1:8000/monitoring/accomplishment_reports/
Content-Type: application/json
Authorization: Token de95d63d55190f47cf0ae40ea1c805752686f6a7

###

# Create an accomplishment report
POST http://127.0.0.1:8000/monitoring/accomplishment_reports/
Content-Type: application/json
Authorization: Token de95d63d55190f47cf0ae40ea1c805752686f6a7

{
    "project": 1,
    "banner_program_title": "Banner Program",
    "flagship_program": "Flagship Initiative",
    "training_modality": "Blended",
    "actual_implementation_date": "2024-12-10",
    "total_number_of_days": 3,
    "submitted_by": 4,
    "project_narrative": 1
}

###

# Get project narratives
GET http://127.0.0.1:8000/monitoring/project_narratives/
Content-Type: application/json
Authorization: Token de95d63d55190f47cf0ae40ea1c805752686f6a7

###

# Create a project narrative
POST http://127.0.0.1:8000/monitoring/project_narratives/
Content-Type: application/json
Authorization: Token de95d63d55190f47cf0ae40ea1c805752686f6a7

{
    "project": 1,
    "phase_description": "Phase Initial",
    "activities_topics": "Digital Training",
    "issues_challenges": "Lack of equipment",
    "participant_engagement_quality": "Very Good",
    "discussion_comments": "Improved after training",
    "ways_forward_plans": "Provide more resources"
}

###

# Get all checklist assignments
GET http://127.0.0.1:8000/monitoring/checklist_assignments/
Content-Type: application/json
Authorization: Token de95d63d55190f47cf0ae40ea1c805752686f6a7

###

# Get details of a specific checklist assignment
GET http://127.0.0.1:8000/monitoring/project/1/checklist_item_submissions/
Content-Type: application/json
Authorization: Token de95d63d55190f47cf0ae40ea1c805752686f6a7

###

# Assign a checklist item to a proponent de95d63d55190f47cf0ae40ea1c805752686f6a7
POST http://127.0.0.1:8000/monitoring/assign/checklist_items/
Content-Type: application/json
Authorization: Token de95d63d55190f47cf0ae40ea1c805752686f6a7

{
    "project": 1,
    "proponent": 1,
    "checklist_items": {
        "daily_attendance": true,
        "summary_of_evaluation": false,
        "modules_lecture_notes": true,
        "other_files": true,
        "photo_documentation": true
    }
}



###

# Mark a checklist assignment as completed
POST http://127.0.0.1:8000/monitoring_evaluation/checklist_assignments/3/mark-completed/
Content-Type: application/json
Authorization: Token de95d63d55190f47cf0ae40ea1c805752686f6a7

{}

###

# Calculate progress for a project
GET http://127.0.0.1:8000/monitoring_evaluation/checklist-progress/4/
Content-Type: application/json
Authorization: Token de95d63d55190f47cf0ae40ea1c805752686f6a7

###

# View proponents assigned to a checklist item
GET http://127.0.0.1:8000/monitoring/checklist_assignments/4/proponents/
Content-Type: application/json
Authorization: Token de95d63d55190f47cf0ae40ea


### Get Checklist Item Submissions
GET http://127.0.0.1:8000/monitoring/project/1/checklist_submissions/
Authorization: Token de95d63d55190f47cf0ae40ea1c805752686f6a7


### Upload Daily Attendance
POST http://127.0.0.1:8000/monitoring/upload/attendance/1/
Content-Type: multipart/form-data
Authorization: Token de95d63d55190f47cf0ae40ea1c805752686f6a7

{
    "proponent": 1,
    "project": 1,
    "file": "dummy_file.txt"
}

### Upload Evaluation Summary
POST http://127.0.0.1:8000/monitoring/upload/evaluation/
Content-Type: multipart/form-data
Authorization: Token de95d63d55190f47cf0ae40ea1c805752686f6a7

{
    "proponent": 1,
    "project": 1,
    "summary_file": "dummy_evaluation.pdf"
}

### Upload Modules/Lecture Notes
POST http://127.0.0.1:8000/upload/lecture_notes/
Content-Type: multipart/form-data
Authorization: Token de95d63d55190f47cf0ae40ea1c805752686f6a7

{
    "proponent": 1,
    "project": 1,
    "module_file": "dummy_notes.pdf"
}

### Upload Photo Documentation
POST http://127.0.0.1:8000/upload/photo/
Content-Type: multipart/form-data
Authorization: Token de95d63d55190f47cf0ae40ea1c805752686f6a7

{
    "proponent": 1,
    "project": 1,
    "photo": "dummy_photo.jpg"
}

### Upload Other Files
POST http://127.0.0.1:8000/upload/other_files/
Content-Type: multipart/form-data
Authorization: Token de95d63d55190f47cf0ae40ea1c805752686f6a7

{
    "proponent": 1,
    "project": 1,
    "photo": "nothing.pdf"
}