###
# Get Accomplishment Reports by User
GET http://127.0.0.1:8000/monitoring/accomplishment_reports/
Authorization: Token 674505cd58b096afbefa3d9f2a0c6c3ace6ee0df

###
# Delete Accomplishment Report by report ID
DELETE http://127.0.0.1:8000/monitoring/accomplishment_reports/2/
Authorization: Token c3a1f99c5cb49b5e5e536f3eef1f8a0501326cbc






# SA REFINED NI NGA ACCOMPLISHMENT - input fields ang naa here
###
POST http://127.0.0.1:8000/monitoring/accomplishment_reports/
Authorization: Token 674505cd58b096afbefa3d9f2a0c6c3ace6ee0df
Content-Type: application/json

{
  "project": 1,
  "banner_program_title": "TISTING KUNG GAGANA NI ANG POST REQUEST",
  "flagship_program": "Flagship Program 1",
  "training_modality": "Face to Face",
  "actualStartDateImplementation": "2024-12-01",
  "actualEndDateImplementation": "2024-12-05",
  "activities_topics": "Workshops and discussions on advanced topics.",
  "issues_challenges": "Lack of participation on day 2.",
  "participant_engagement_quality": "Highly interactive session.",
  "discussion_comments": "Comments from participants were positive.",
  "ways_forward_plans": "Plan to conduct follow-up sessions."
}

