###
# Get Accomplishment Reports by User
GET http://127.0.0.1:8000/monitoring/accomplishment_reports/
Authorization: Token 12a635010f053b86064b3762efa53a411dcef350

###
# Delete Accomplishment Report by report ID
DELETE http://127.0.0.1:8000/monitoring/accomplishment_reports/2/
Authorization: Token 12a635010f053b86064b3762efa53a411dcef350






# SA REFINED NI NGA ACCOMPLISHMENT - input fields ang naa here
###
POST http://127.0.0.1:8000/monitoring/accomplishment_reports/
Authorization: Token 12a635010f053b86064b3762efa53a411dcef350
Content-Type: application/json

{
  "project": 2,
  "banner_program_title": "TRY 01-16-25 - clrice",
  "flagship_program": "Flagship Program 1",
  "training_modality": "Face to Face",
  "actualStartDateImplementation": "2024-12-01",
  "actualEndDateImplementation": "2024-12-05",
  "activities_topics": "Workshops and discussions on advanced topics.",
  "issues_challenges": "Lack of participation on day 2.",
  "participant_engagement_quality": "Highly interactive session.",
  "discussion_comments": "Comments from participants were positive.",
  "ways_forward_plans": "Plan to conduct follow-up sessions."
}

