# FOR OP 2

### Fetch All Extension Program OP2 Entries
GET http://127.0.0.1:8000/monitoring/extension_program_op2/
Authorization: Token 75b5414156c3e55e5504a15533dfad5323c2bb0d
Accept: application/json

###

### Create a New Extension Program OP2 Entry
POST http://127.0.0.1:8000/monitoring/extension_program_op2/
Authorization: Token 75b5414156c3e55e5504a15533dfad5323c2bb0d
Content-Type: application/json

{
    "mandated_priority_program": "Example Mandated Program",
    "quarter": "2nd Quarter",
    "extension_program": "Example Extension Program",
    "from_date": "2024-01-01",
    "to_date": "2024-12-31",
    "campus": "Example Campus",
    "remarks": "Some remarks"
}

###

### Update an Existing Extension Program OP2 Entry (Replace <id> with an actual record ID)
PUT http://127.0.0.1:8000/monitoring/extension_program_op2/1/
Authorization: Token 75b5414156c3e55e5504a15533dfad5323c2bb0d
Content-Type: application/json

{
    "mandated_priority_program": "Updated Priority Program",
    "quarter": "1st Quarter",
    "extension_program": "Updated Extension Program",
    "from_date": "2024-02-01",
    "to_date": "2024-12-31",
    "campus": "Updated Campus",
    "remarks": "Updated remarks"
}

###

### Delete an Extension Program OP2 Entry (Replace <id> with an actual record ID)
DELETE http://127.0.0.1:8000/monitoring/extension_program_op2/2/
Authorization: Token 75b5414156c3e55e5504a15533dfad5323c2bb0d
Accept: application/json


# -----------------------------
# FOR OC

### Fetch All Extension Program OC Entries
GET http://127.0.0.1:8000/monitoring/extension_program_oc/
Authorization: Token 75b5414156c3e55e5504a15533dfad5323c2bb0d
Accept: application/json

###

### Create a New Extension Program OC Entry
POST http://127.0.0.1:8000/monitoring/extension_program_oc/
Authorization: Token 75b5414156c3e55e5504a15533dfad5323c2bb0d
Content-Type: application/json

{
    "memorandum_of_agreements": "Institute of Integrated Electrical Engineers",
    "extension_program": "Bigay Liwanag",
    "from_date": "2024-01-01",
    "to_date": "2024-03-01",
    "campus": "CEA",
    "remarks": "Program completed successfully."
}

###

### Update an Existing Extension Program OC Entry (Replace <id> with an actual record ID)
PUT http://127.0.0.1:8000/monitoring/extension_program_oc/1/
Authorization: Token 75b5414156c3e55e5504a15533dfad5323c2bb0d
Content-Type: application/json

{
    "memorandum_of_agreements": "Updated 2 MOA Name",
    "extension_program": "Updated 2 Program Name",
    "from_date": "2024-02-01",
    "to_date": "2024-04-01",
    "campus": "Updated Campus Name",
    "remarks": "Updated remarks."
}

###

### Delete an Extension Program OC Entry (Replace <id> with an actual record ID)
DELETE http://127.0.0.1:8000/monitoring/extension_program_oc/1/
Authorization: Token 75b5414156c3e55e5504a15533dfad5323c2bb0d
Accept: application/json


# -----------------------------
# FOR College Performance

### Get all rows
GET http://127.0.0.1:8000/monitoring/college_performance/
Authorization: Token 95b4b4cdc399f6cb52408613c1eaffc0f30e4e0a
Content-Type: application/json

###

### Create a new row
POST http://127.0.0.1:8000/monitoring/college_performance/
Authorization: Token 95b4b4cdc399f6cb52408613c1eaffc0f30e4e0a
Content-Type: application/json

{
    "campus": "CITC",
    "programs_number": 10,
    "programs_percentage": 50.0,
    "faculty_number": 5,
    "faculty_percentage": 60.0,
    "average_percentage": 55.0,
    "persons_trained_target": 100,
    "persons_trained_weighted_accomplishment": 90.0,
    "persons_trained_variance": 10.0,
    "partnerships_target": 3,
    "partnerships_accomplishment": 2,
    "partnerships_variance": 1,
    "beneficiaries_target": 70.0,
    "beneficiaries_accomplishment": 65.0,
    "beneficiaries_variance": 5.0,
    "extension_programs_target": 2,
    "extension_programs_accomplishment": 2,
    "extension_programs_variance": 0
}

###

### Update an existing row
PUT http://127.0.0.1:8000/monitoring/college_performance/1/
Authorization: Token 95b4b4cdc399f6cb52408613c1eaffc0f30e4e0a
Content-Type: application/json

{
    "campus": "CEA Updated",
    "programs_number": 12,
    "programs_percentage": 55.0,
    "faculty_number": 6,
    "faculty_percentage": 65.0,
    "average_percentage": 60.0,
    "persons_trained_target": 110,
    "persons_trained_weighted_accomplishment": 95.0,
    "persons_trained_variance": 15.0,
    "partnerships_target": 4,
    "partnerships_accomplishment": 3,
    "partnerships_variance": 1,
    "beneficiaries_target": 75.0,
    "beneficiaries_accomplishment": 70.0,
    "beneficiaries_variance": 5.0,
    "extension_programs_target": 3,
    "extension_programs_accomplishment": 3,
    "extension_programs_variance": 0
}

###

### Delete a row
DELETE http://127.0.0.1:8000/monitoring/college_performance/1/
Authorization: Token 95b4b4cdc399f6cb52408613c1eaffc0f30e4e0a
Content-Type: application/json
