# Generated by Django 5.0.7 on 2024-11-01 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docquestapp', '0005_deliverables_remove_project_routingprogress_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentpdf',
            old_name='contentType',
            new_name='content_type',
        ),
        migrations.RenameField(
            model_name='documentpdf',
            old_name='objectID',
            new_name='source_id',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='contentType',
            new_name='content_type',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='objectID',
            new_name='source_id',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='contentType',
            new_name='content_type',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='objectID',
            new_name='source_id',
        ),
    ]
