# Generated by Django 5.0.7 on 2024-11-04 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docquestapp', '0007_alter_review_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationandmonitoring',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluationAndMonitorings', to='docquestapp.project'),
        ),
        migrations.AlterField(
            model_name='monitoringplanandschedule',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoringPlanSchedules', to='docquestapp.project'),
        ),
        migrations.AlterField(
            model_name='signatories',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatories', to='docquestapp.project'),
        ),
    ]
