# Generated by Django 5.0.7 on 2024-11-06 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docquestapp', '0011_moa_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partneragency',
            name='addressID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partnerAgency', to='docquestapp.address'),
        ),
    ]
