# Generated by Django 5.0.7 on 2024-11-16 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docquestapp', '0016_alter_roles_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='campus',
            field=models.CharField(default='USTP-CDO', max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='college',
            field=models.CharField(default='NO COLLEGE', max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.CharField(default='NO DEPARTMENT', max_length=50),
        ),
    ]
