# Generated by Django 5.0.7 on 2024-11-16 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docquestapp', '0017_alter_customuser_campus_alter_customuser_college_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('collegeID', models.AutoField(primary_key=True, serialize=False)),
                ('abbreviation', models.CharField(max_length=15)),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='college',
        ),
        migrations.RemoveField(
            model_name='project',
            name='program',
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('programID', models.AutoField(primary_key=True, serialize=False)),
                ('abbreviation', models.CharField(max_length=15)),
                ('title', models.CharField(max_length=100)),
                ('collegeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program', to='docquestapp.college')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='program',
            field=models.ManyToManyField(related_name='projectProgram', to='docquestapp.program'),
        ),
    ]
