# Generated by Django 5.0.7 on 2024-11-23 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docquestapp', '0020_campus_remove_customuser_campus_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterModelOptions(
            name='campus',
            options={'verbose_name_plural': 'Campuses'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='college',
            options={'verbose_name_plural': 'Colleges'},
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='deliverables',
            options={'verbose_name_plural': 'Deliverables'},
        ),
        migrations.AlterModelOptions(
            name='faculty',
            options={'verbose_name_plural': 'Faculties'},
        ),
        migrations.AlterModelOptions(
            name='partneragency',
            options={'verbose_name_plural': 'Partner Agencies'},
        ),
        migrations.AlterModelOptions(
            name='program',
            options={'verbose_name_plural': 'Programs'},
        ),
        migrations.AlterModelOptions(
            name='programcategory',
            options={'verbose_name_plural': 'Program Categories'},
        ),
        migrations.AlterModelOptions(
            name='projectcategory',
            options={'verbose_name_plural': 'Project Categories'},
        ),
        migrations.AlterModelOptions(
            name='roles',
            options={'verbose_name_plural': 'Roles'},
        ),
        migrations.AlterField(
            model_name='college',
            name='campusID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='campus', to='docquestapp.campus'),
            preserve_default=False,
        ),
    ]
