# Generated by Django 5.0.7 on 2024-11-26 09:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docquestapp', '0021_alter_address_options_alter_campus_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectApprovalWorkflow',
            fields=[
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='approval_workflow', serialize=False, to='docquestapp.project')),
                ('overall_status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('total_approvals_required', models.IntegerField(default=0)),
                ('current_approvals', models.IntegerField(default=0)),
                ('workflow_started_at', models.DateTimeField(auto_now_add=True)),
                ('workflow_completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='project',
            old_name='targetImplementation',
            new_name='targetEndDateImplementation',
        ),
        migrations.AddField(
            model_name='project',
            name='targetStartDateImplementation',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ProgramChairApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('comments', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_chair_project_approvals', to='docquestapp.program')),
                ('program_chair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_chair_project_reviews', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_chair_approvals', to='docquestapp.projectapprovalworkflow')),
            ],
            options={
                'unique_together': {('workflow', 'program', 'program_chair')},
            },
        ),
        migrations.CreateModel(
            name='CollegeDeanApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('comments', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='college_dean_project_approvals', to='docquestapp.college')),
                ('college_dean', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='college_dean_project_reviews', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='college_dean_approvals', to='docquestapp.projectapprovalworkflow')),
            ],
            options={
                'unique_together': {('workflow', 'college', 'college_dean')},
            },
        ),
    ]
