# Generated by Django 5.0.7 on 2024-11-28 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docquestapp', '0022_projectapprovalworkflow_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='programchairapproval',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='programchairapproval',
            name='program',
        ),
        migrations.RemoveField(
            model_name='programchairapproval',
            name='program_chair',
        ),
        migrations.RemoveField(
            model_name='programchairapproval',
            name='workflow',
        ),
        migrations.RemoveField(
            model_name='projectapprovalworkflow',
            name='project',
        ),
        migrations.AddField(
            model_name='review',
            name='collegeID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='docquestapp.college'),
        ),
        migrations.AddField(
            model_name='review',
            name='sequence',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='CollegeDeanApproval',
        ),
        migrations.DeleteModel(
            name='ProgramChairApproval',
        ),
        migrations.DeleteModel(
            name='ProjectApprovalWorkflow',
        ),
    ]
