# Generated by Django 5.1.2 on 2024-10-09 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccomplishmentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_summary', models.TextField()),
                ('submission_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_date', models.DateField()),
                ('overall_score', models.IntegerField()),
                ('comments', models.TextField()),
                ('evaluator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(max_length=255)),
                ('doc_file', models.FileField(upload_to='project_documents/')),
                ('upload_date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='project',
        ),
        migrations.RemoveField(
            model_name='communication',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='communication',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='evaluation',
            name='evaluator',
        ),
        migrations.RemoveField(
            model_name='evaluation',
            name='project',
        ),
        migrations.RemoveField(
            model_name='project',
            name='office',
        ),
        migrations.DeleteModel(
            name='Trainer',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_leader',
        ),
        migrations.AddField(
            model_name='accomplishmentreport',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accomplishment_reports', to='monitoring.project'),
        ),
        migrations.AddField(
            model_name='accomplishmentreport',
            name='submitted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evaluationsummary',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_summaries', to='monitoring.project'),
        ),
        migrations.AddField(
            model_name='projectdocument',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='monitoring.project'),
        ),
        migrations.AddField(
            model_name='projectdocument',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='Communication',
        ),
        migrations.DeleteModel(
            name='Evaluation',
        ),
        migrations.DeleteModel(
            name='Office',
        ),
    ]
