# Generated by Django 5.0.7 on 2024-11-01 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docquestapp', '0003_rename_projectid_budgetrequirementsitems_project_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectactivities',
            old_name='personResponsibleID',
            new_name='personResponsible',
        ),
    ]
