# Generated by Django 5.0.7 on 2024-11-01 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('docquestapp', '0004_alter_evaluationandmonitoring_indicators_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deliverables',
            fields=[
                ('deliverableID', models.AutoField(primary_key=True, serialize=False)),
                ('deliverableName', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='routingProgress',
        ),
        migrations.RemoveField(
            model_name='signatories',
            name='approvalStatus',
        ),
        migrations.RemoveField(
            model_name='signatories',
            name='signatureCode',
        ),
        migrations.RemoveField(
            model_name='signatories',
            name='userID',
        ),
        migrations.AddField(
            model_name='project',
            name='proponents',
            field=models.ManyToManyField(related_name='proponent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='signatories',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='signatories',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='DocumentPDF',
            fields=[
                ('documentID', models.AutoField(primary_key=True, serialize=False)),
                ('fileData', models.BinaryField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('objectID', models.PositiveIntegerField()),
                ('contentType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='NonUserProponents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nonUserProponents', to='docquestapp.project')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notificationID', models.AutoField(primary_key=True, serialize=False)),
                ('objectID', models.PositiveIntegerField()),
                ('message', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Unread', 'Unread'), ('Read', 'Read')], default='Unread', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('contentType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('reviewID', models.AutoField(primary_key=True, serialize=False)),
                ('objectID', models.PositiveIntegerField()),
                ('reviewStatus', models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('reviewDate', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField()),
                ('contentOwnerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewsContentOwner', to=settings.AUTH_USER_MODEL)),
                ('contentType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('reviewedByID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewsReviewedBy', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProjectDeliverables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliverableID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userProjectDeliverables', to='docquestapp.deliverables')),
                ('projectID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userProjectDeliverables', to='docquestapp.project')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userProjectDeliverables', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Proponents',
        ),
    ]
