# Generated by Django 5.0.7 on 2024-11-11 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docquestapp', '0013_alter_evaluationandmonitoring_indicators_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstParty',
            fields=[
                ('firstPartyID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('moaID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firstParty', to='docquestapp.moa')),
            ],
        ),
        migrations.CreateModel(
            name='SecondParty',
            fields=[
                ('secondPartyID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('moaID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondParty', to='docquestapp.moa')),
            ],
        ),
        migrations.CreateModel(
            name='Witnesses',
            fields=[
                ('witnessID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('moaID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='witnesses', to='docquestapp.moa')),
            ],
        ),
    ]
