# Generated by Django 5.0.7 on 2024-11-05 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docquestapp', '0010_alter_moa_datecreated'),
    ]

    operations = [
        migrations.AddField(
            model_name='moa',
            name='userID',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, related_name='moaUser', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
